eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    loadbalancer:
      ribbon:
        enable: false


